default: -t "not @benchmarking" -t "not @pending" -t "not @local-network" -t "not @notintegration"
test: -t "not @pending" -t "not @nottest"
integration: -t "not @pending" -t "not @notintegration"
staging: -t "not @pending" -t "not @notstaging"
production: -t "not @pending" -t "not @notproduction"
staging_aws: -t "not @pending" -t "not @notstaging"
production_aws: -t "not @pending" -t "not @notproduction"
